services:
  - type: web
    name: logo-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app_tflite:app"
    envVars:
      PYTHON_VERSION: 3.10.12
